name: Build
on: [push, pull_request]
jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Build
        run: make
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6
      - name: Build
        run: make
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6
      - name: Add MinGW to PATH
        run: echo "C:\msys64\mingw32\bin" >> $GITHUB_PATH
        shell: bash
      - name: Build
        run: make
        shell: bash
        env:
          CC: gcc
